packages:
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - workerd

overrides:
  vite: "catalog:"
  vitest: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vitest: 4.1.10
  vite-plus: 0.2.5
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
